[package]
name = "atcoder_template"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
itertools = "0.9.0"
proconio = { version = "=0.4.5", features = ["derive"] }
superslice = "1.0.0"

[dev-dependencies]
cli_test_dir = "*"
